# Generated by Django 3.2.7 on 2021-10-10 14:41

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid
import versionfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ConreqPackage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('long_description', models.FileField(upload_to='app_store/readme/')),
                ('long_description_type', models.CharField(choices=[('text/plain', 'Plain Text (.txt)'), ('text/x-rst', 'reStructuredText (.rst)'), ('text/markdown', 'Markdown (.md)')], default='text/markdown', max_length=20)),
                ('development_stage', models.CharField(choices=[('1 - Planning', 'Planning'), ('2 - Pre-Alpha', 'Pre-Alpha'), ('3 - Alpha', 'Alpha'), ('4 - Beta', 'Beta'), ('5 - Production/Stable', 'Stable'), ('6 - Mature', 'Mature'), ('7 - Inactive', 'Inactive')], default='2 - Pre-Alpha', max_length=21)),
                ('version', versionfield.fields.VersionField(default='0.0.1')),
                ('banner_message', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('author_url', models.URLField(blank=True, null=True)),
                ('repository_url', models.URLField()),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('support_url', models.URLField(blank=True, null=True)),
                ('donation_url', models.URLField(blank=True, null=True)),
                ('pypi_url', models.URLField(blank=True, null=True)),
                ('license_url', models.URLField(blank=True, null=True)),
                ('license_type', models.CharField(choices=[('GPL3', 'GNU GPL v3'), ('MIT', 'MIT License'), ('APACHE2', 'Apache License 2.0'), ('BSD2', 'BSD 2-Clause Simplified License'), ('BSD3', 'BSD 3-Clause Revised License'), ('ECLIPSE2', 'Eclipse Public License 2.0'), ('AGPL3', 'GNU AGPL v3'), ('GPL2', 'GNU GPL v2'), ('LGPL2_1', 'GNU LGPL v2.1'), ('LGPL3', 'GNU LGPL v3'), ('MOZ2', 'Mozilla Public License 2.0'), ('UNLICENSE', 'The Unlicense'), ('OTHER', 'Other')], default='GPL3', max_length=20)),
                ('sys_platforms', multiselectfield.db.fields.MultiSelectField(choices=[('AIX', 'Aix'), ('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('CYGWIN', 'Cygwin'), ('MACOS', 'Darwin')], max_length=10)),
                ('desktop_compatible', models.BooleanField()),
                ('touch_compatible', models.BooleanField()),
                ('mobile_compatible', models.BooleanField()),
                ('minimum_conreq_version', versionfield.fields.VersionField(default='0.0.1')),
                ('tested_conreq_version', versionfield.fields.VersionField(default='1.0.0')),
                ('max_conreq_version', versionfield.fields.VersionField(blank=True, null=True)),
                ('asynchronous', models.CharField(choices=[('NONE', 'Not Async'), ('SEMI', 'Partially Async'), ('FULL', 'Fully Async')], default='NONE', max_length=20)),
                ('incompatible_categories', models.ManyToManyField(blank=True, related_name='incompatible_categories', to='app_store.Category')),
                ('incompatible_conreq_packages', models.ManyToManyField(blank=True, related_name='_app_store_conreqpackage_incompatible_conreq_packages_+', to='app_store.ConreqPackage')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='app_store/screenshot/')),
                ('conreq_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.conreqpackage')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeMessage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('conreq_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.conreqpackage')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('example_values', models.CharField(blank=True, max_length=255, null=True)),
                ('conreq_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.conreqpackage')),
            ],
        ),
        migrations.AddField(
            model_name='conreqpackage',
            name='incompatible_subcategories',
            field=models.ManyToManyField(blank=True, related_name='incompatible_subcategories', to='app_store.Subcategory'),
        ),
        migrations.AddField(
            model_name='conreqpackage',
            name='optional_conreq_packages',
            field=models.ManyToManyField(blank=True, related_name='_app_store_conreqpackage_optional_conreq_packages_+', to='app_store.ConreqPackage'),
        ),
        migrations.AddField(
            model_name='conreqpackage',
            name='required_conreq_packages',
            field=models.ManyToManyField(blank=True, related_name='_app_store_conreqpackage_required_conreq_packages_+', to='app_store.ConreqPackage'),
        ),
        migrations.AddField(
            model_name='conreqpackage',
            name='subcategories',
            field=models.ManyToManyField(to='app_store.Subcategory'),
        ),
    ]
