# Generated by Django 3.2.7 on 2021-10-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppackage',
            name='desktop_compatible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
