# Generated by Django 3.2.7 on 2021-10-10 17:53

import conreq_app_store.internal.app_store.helpers
import conreq_app_store.internal.app_store.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conreqpackage',
            name='long_description',
            field=models.FileField(upload_to=conreq_app_store.internal.app_store.helpers.readme_path, validators=[conreq_app_store.internal.app_store.validators.readme_extension_validator]),
        ),
        migrations.AlterField(
            model_name='conreqpackage',
            name='sys_platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AIX', 'Aix'), ('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('CYGWIN', 'Cygwin'), ('MACOS', 'Darwin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to=conreq_app_store.internal.app_store.helpers.screenshots_path),
        ),
    ]
