# Generated by Django 3.2.7 on 2021-10-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_apppackage_desktop_compatible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppackage',
            name='license_type',
            field=models.CharField(choices=[('GPL3', 'GNU GPL v3'), ('MIT', 'MIT License'), ('APACHE2', 'Apache License 2.0'), ('BSD2', 'BSD 2-Clause Simplified License'), ('BSD3', 'BSD 3-Clause Revised License'), ('ECLIPSE2', 'Eclipse Public License 2.0'), ('AGPL3', 'GNU AGPL v3'), ('GPL2', 'GNU GPL v2'), ('LGPL2_1', 'GNU LGPL v2.1'), ('LGPL3', 'GNU LGPL v3'), ('MOZ2', 'Mozilla Public License 2.0'), ('UNLICENSE', 'The Unlicense'), ('OTHER', 'Other')], default='GPL3', max_length=20),
        ),
    ]
