# Generated by Django 3.2.7 on 2021-10-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_rename_sys_platforms_conreqpackage_system_platforms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conreqpackage',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='conreqpackage',
            name='version',
        ),
        migrations.AlterField(
            model_name='conreqpackage',
            name='pypi_url',
            field=models.URLField(blank=True, help_text='Releases are pulled from PyPi by default.', null=True),
        ),
        migrations.AlterField(
            model_name='conreqpackage',
            name='repository_url',
            field=models.URLField(help_text='If not using PyPi, then tagged releases are mandatory.'),
        ),
    ]
