# Generated by Django 3.2.7 on 2021-10-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_auto_20211010_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppackage',
            name='author_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
