# Generated by Django 3.2.7 on 2021-10-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0006_apppackage_author_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
