# Generated by Django 3.2.7 on 2021-10-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0007_auto_20211010_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentvariable',
            old_name='default',
            new_name='default_value',
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
