# Generated by Django 3.2.7 on 2021-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0009_rename_example_environmentvariable_example_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticemessage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='mark_read',
        ),
        migrations.AddField(
            model_name='noticemessage',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
