# Generated by Django 3.2.7 on 2021-10-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0010_auto_20211010_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apppackage',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='apppackage',
            name='verbose_name',
        ),
        migrations.AddField(
            model_name='apppackage',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
